# Generated by Django 4.1.5 on 2023-01-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_limity', models.IntegerField()),
                ('bedrooms', models.IntegerField(default=1, verbose_name='Bedrooms Avaliable')),
                ('beds', models.IntegerField(default=1, verbose_name='Beds Avaliable')),
                ('bathrooms', models.IntegerField(default=1, verbose_name='Bathrooms Avaliable')),
                ('pet_friendly', models.BooleanField(default=True, verbose_name='Are pets allowed?')),
                ('cleaning_fee', models.FloatField(verbose_name='Cleaning service fee')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
        ),
    ]
