# Generated by Django 4.1.5 on 2023-01-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_rename_property_advertisement_room'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Properties',
            new_name='Rooms',
        ),
    ]
