# Generated by Django 4.1.5 on 2023-01-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_rooms_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='price',
            field=models.PositiveIntegerField(default=100, verbose_name='Price per night'),
        ),
    ]
