# Generated by Django 4.1.5 on 2023-01-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_rooms_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='bathrooms',
            field=models.PositiveIntegerField(default=1, verbose_name='Bathrooms Avaliable'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='bedrooms',
            field=models.PositiveIntegerField(default=1, verbose_name='Bedrooms Avaliable'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='beds',
            field=models.PositiveIntegerField(default=1, verbose_name='Beds Avaliable'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='guest_limity',
            field=models.PositiveIntegerField(),
        ),
    ]
